extends Node

var pokemon = {
	"0" : {
		"name" : "BULBASAUR",
		"type1" : "GRASS",
		"type2" : "POISON",
		"HP" : 45,
		"ATTACK" : 49,
		"DEFENSE" : 49,
		"SPECIAL" : 65,
		"SPEED" : 45,
		"TIER": "LOW"
		},
	"1" : {
		"name" : "IVYSAUR", 
		"type1" : "GRASS", 
		"type2" : "POISON",
		"HP" : 60,
		"ATTACK" : 62,
		"DEFENSE" : 63,
		"SPECIAL" : 80,
		"SPEED" : 60,
		"TIER": "LOWMID"
		},
	"2" : {
		"name" : "VENUSAUR", 
		"type1" : "GRASS", 
		"type2" : "POISON",
		"HP" : 80,
		"ATTACK" : 82,
		"DEFENSE" : 83,
		"SPECIAL" : 100,
		"SPEED" : 80,
		"TIER": "MID"
		},
	"3" : {
		"name" : "CHARMANDER", 
		"type1" : "FIRE", 
		"type2" : "NULL",
		"HP" : 39,
		"ATTACK" : 52,
		"DEFENSE" : 43,
		"SPECIAL" : 50,
		"SPEED" : 65,
		"TIER": "LOW"
		},
	"4" : {
		"name" : "CHARMELEON", 
		"type1" : "FIRE", 
		"type2" : "NULL",
		"HP" : 58,
		"ATTACK" : 64,
		"DEFENSE" : 58,
		"SPECIAL" : 65,
		"SPEED" : 80,
		"TIER": "LOWMID"
		},
	"5" : {
		"name" : "CHARIZARD", 
		"type1" : "FIRE", 
		"type2" : "FLYING",
		"HP" : 78,
		"ATTACK" : 84,
		"DEFENSE" : 78,
		"SPECIAL" : 85,
		"SPEED" : 100,
		"TIER": "MID"
		},
	"6" : {"name" : "SQUIRTLE", "type1" : "WATER", "type2" : "NULL"},
	"7" : {"name" : "WARTORTLE", "type1" : "WATER", "type2" : "NULL"},
	"8" : {"name" : "BLASTOISE", "type1" : "WATER", "type2" : "NULL"},
	"9" : {"name" : "CATERPIE", "type1" : "BUG", "type2" : "NULL"},
	"10" : {"name" : "METAPOD", "type1" : "BUG", "type2" : "NULL"},
	"11" : {"name" : "BUTTERFREE", "type1" : "BUG", "type2" : "FLYING"},
	"12" : {"name" : "WEEDLE", "type1" : "BUG", "type2" : "POISON"},
	"13" : {"name" : "KAKUNA", "type1" : "BUG", "type2" : "POISON"},
	"14" : {"name" : "BEEDRILL", "type1" : "BUG", "type2" : "POISON"},
	"15" : {"name" : "PIDGEY", "type1" : "NORMAL", "type2" : "FLYING"},
	"16" : {"name" : "PIDGEOTTO", "type1" : "NORMAL", "type2" : "FLYING"},
	"17" : {"name" : "PIDGEOT", "type1" : "NORMAL", "type2" : "FLYING"},
	"18" : {"name" : "RATTATA", "type1" : "NORMAL", "type2" : "NULL"},
	"19" : {"name" : "RATICATE", "type1" : "NORMAL", "type2" : "NULL"},
	"20" : {"name" : "SPEAROW", "type1" : "NORMAL", "type2" : "FLYING"},
	"21" : {"name" : "FEAROW", "type1" : "NORMAL", "type2" : "FLYING"},
	"22" : {"name" : "EKANS", "type1" : "POISON", "type2" : "NULL"},
	"23" : {"name" : "ARBOK", "type1" : "POISON", "type2" : "NULL"},
	"24" : {
		"name" : "PIKACHU", 
		"type1" : "ELECTRIC", 
		"type2" : "NULL",
		"HP" : 35,
		"ATTACK" : 55,
		"DEFENSE" : 30,
		"SPECIAL" : 50,
		"SPEED" : 90,
		"TIER": "LOW"
		},
	"25" : {"name" : "RAICHU", "type1" : "ELECTRIC", "type2" : "NULL"},
	"26" : {"name" : "SANDSHREW", "type1" : "GROUND", "type2" : "NULL"},
	"27" : {"name" : "SANDSLASH", "type1" : "GROUND", "type2" : "NULL"},
	"28" : {"name" : "NIDORAN F", "type1" : "POISON", "type2" : "NULL"},
	"29" : {"name" : "NIDORINA", "type1" : "POISON", "type2" : "NULL"},
	"30" : {"name" : "NIDOQUEEN", "type1" : "POISON", "type2" : "GROUND"},
	"31" : {"name" : "NIDORAN M", "type1" : "POISON", "type2" : "NULL"},
	"32" : {"name" : "NIDORINO", "type1" : "POISON", "type2" : "NULL"},
	"33" : {"name" : "NIDOKING", "type1" : "POISON", "type2" : "GROUND"},
	"34" : {"name" : "CLEFAIRY", "type1" : "NORMAL", "type2" : "NULL"},
	"35" : {"name" : "CLEFABLE", "type1" : "NORMAL", "type2" : "NULL"},
	"36" : {"name" : "VULPIX", "type1" : "FIRE", "type2" : "NULL"},
	"37" : {"name" : "NINETALES", "type1" : "FIRE", "type2" : "NULL"},
	"38" : {"name" : "JIGGLYPUFF", "type1" : "NORMAL", "type2" : "NULL"},
	"39" : {"name" : "WIGGLYTUFF", "type1" : "NORMAL", "type2" : "NULL"},
	"40" : {"name" : "ZUBAT", "type1" : "POISON", "type2" : "FLYING"},
	"41" : {"name" : "GOLBAT", "type1" : "POISON", "type2" : "FLYING"},
	"42" : {"name" : "ODDISH", "type1" : "GRASS", "type2" : "POISON"},
	"43" : {"name" : "GLOOM", "type1" : "GRASS", "type2" : "POISON"},
	"44" : {"name" : "VILEPLUME", "type1" : "GRASS", "type2" : "POISON"},
	"45" : {"name" : "PARAS", "type1" : "BUG", "type2" : "GRASS"},
	"46" : {"name" : "PARASECT", "type1" : "BUG", "type2" : "GRASS"},
	"47" : {"name" : "VENONAT", "type1" : "BUG", "type2" : "POISON"},
	"48" : {"name" : "VENOMOTH", "type1" : "BUG", "type2" : "POISON"},
	"49" : {"name" : "DIGLETT", "type1" : "GROUND", "type2" : "NULL"},
	"50" : {"name" : "DUGTRIO", "type1" : "GROUND", "type2" : "NULL"},
	"51" : {"name" : "MEOWTH", "type1" : "NORMAL", "type2" : "NULL"},
	"52" : {"name" : "PERSIAN", "type1" : "NORMAL", "type2" : "NULL"},
	"53" : {"name" : "PSYDUCK", "type1" : "WATER", "type2" : "NULL"},
	"54" : {"name" : "GOLDUCK", "type1" : "WATER", "type2" : "NULL"},
	"55" : {"name" : "MANKEY", "type1" : "FIGHTING", "type2" : "NULL"},
	"56" : {"name" : "PRIMEAPE", "type1" : "FIGHTING", "type2" : "NULL"},
	"57" : {"name" : "GROWLITHE", "type1" : "FIRE", "type2" : "NULL"},
	"58" : {"name" : "ARCANINE", "type1" : "FIRE", "type2" : "NULL"},
	"59" : {"name" : "POLIWAG", "type1" : "WATER", "type2" : "NULL"},
	"60" : {"name" : "POLIWHIRL", "type1" : "WATER", "type2" : "NULL"},
	"61" : {"name" : "POLIWRATH", "type1" : "WATER", "type2" : "NULL"},
	"62" : {"name" : "ABRA", "type1" : "PSYCHIC", "type2" : "NULL"},
	"63" : {"name" : "KADABRA", "type1" : "PSYCHIC", "type2" : "NULL"},
	"64" : {"name" : "ALAKAZAM", "type1" : "PSYCHIC", "type2" : "NULL"},
	"65" : {"name" : "MACHOP", "type1" : "FIGHTING", "type2" : "NULL"},
	"66" : {"name" : "MACHOKE", "type1" : "FIGHTING", "type2" : "NULL"},
	"67" : {"name" : "MACHAMP", "type1" : "FIGHTING", "type2" : "NULL"},
	"68" : {"name" : "BELLSPROUT", "type1" : "GRASS", "type2" : "POISON"},
	"69" : {"name" : "WEEPINBELL", "type1" : "GRASS", "type2" : "POISON"},
	"70" : {"name" : "VICTREEBEL", "type1" : "GRASS", "type2" : "POISON"},
	"71" : {"name" : "TENTACOOL", "type1" : "WATER", "type2" : "POISON"},
	"72" : {"name" : "TENTACRUEL", "type1" : "WATER", "type2" : "POISON"},
	"73" : {"name" : "GEODUDE", "type1" : "ROCK", "type2" : "GROUND"},
	"74" : {"name" : "GRAVELER", "type1" : "ROCK", "type2" : "GROUND"},
	"75" : {"name" : "GOLEM", "type1" : "ROCK", "type2" : "GROUND"},
	"76" : {"name" : "PONYTA", "type1" : "FIRE", "type2" : "NULL"},
	"77" : {"name" : "RAPIDASH", "type1" : "FIRE", "type2" : "NULL"},
	"78" : {"name" : "SLOWPOKE", "type1" : "WATER", "type2" : "PSYCHIC"},
	"79" : {"name" : "SLOWBRO", "type1" : "WATER", "type2" : "PSYCHIC"},
	"80" : {"name" : "MAGNEMITE", "type1" : "ELECTRIC", "type2" : "NULL"},
	"81" : {"name" : "MAGNETON", "type1" : "ELECTRIC", "type2" : "NULL"},
	"82" : {"name" : "FARFETCH'D", "type1" : "NORMAL", "type2" : "FLYING"},
	"83" : {"name" : "DODUO", "type1" : "NORMAL", "type2" : "FLYING"},
	"84" : {"name" : "DODRIO", "type1" : "NORMAL", "type2" : "FLYING"},
	"85" : {"name" : "SEEL", "type1" : "WATER", "type2" : "NULL"},
	"86" : {"name" : "DEWGONG", "type1" : "WATER", "type2" : "ICE"},
	"87" : {"name" : "GRIMER", "type1" : "POISON", "type2" : "NULL"},
	"88" : {"name" : "MUK", "type1" : "POISON", "type2" : "NULL"},
	"89" : {"name" : "SHELLDER", "type1" : "WATER", "type2" : "NULL"},
	"90" : {"name" : "CLOYSTER", "type1" : "WATER", "type2" : "ICE"},
	"91" : {"name" : "GASTLY", "type1" : "GHOST", "type2" : "POISON"},
	"92" : {"name" : "HAUNTER", "type1" : "GHOST", "type2" : "POISON"},
	"93" : {"name" : "GENGAR", "type1" : "GHOST", "type2" : "POISON"},
	"94" : {"name" : "ONIX", "type1" : "ROCK", "type2" : "GROUND"},
	"95" : {"name" : "DROWZEE", "type1" : "PSYCHIC", "type2" : "NULL"},
	"96" : {"name" : "HYPNO", "type1" : "PSYCHIC", "type2" : "NULL"},
	"97" : {"name" : "KRABBY", "type1" : "WATER", "type2" : "NULL"},
	"98" : {"name" : "KINGLER", "type1" : "WATER", "type2" : "NULL"},
	"99" : {"name" : "VOLTORB", "type1" : "ELECTRIC", "type2" : "NULL"},
	"100" : {"name" : "ELECTRODE", "type1" : "ELECTRIC", "type2" : "NULL"},
	"101" : {"name" : "EXEGGCUTE", "type1" : "GRASS", "type2" : "PSYCHIC"},
	"102" : {"name" : "EXEGGUTOR", "type1" : "GRASS", "type2" : "PSYCHIC"},
	"103" : {"name" : "CUBONE", "type1" : "GROUND", "type2" : "NULL"},
	"104" : {"name" : "MAROWAK", "type1" : "GROUND", "type2" : "NULL"},
	"105" : {"name" : "HITMONLEE", "type1" : "FIGHTING", "type2" : "NULL"},
	"106" : {"name" : "HITMONCHAN", "type1" : "FIGHTING", "type2" : "NULL"},
	"107" : {"name" : "LICKITUNG", "type1" : "NORMAL", "type2" : "NULL"},
	"108" : {"name" : "KOFFING", "type1" : "POISON", "type2" : "NULL"},
	"109" : {"name" : "WEEZING", "type1" : "POISON", "type2" : "NULL"},
	"110" : {"name" : "RHYHORN", "type1" : "GROUND", "type2" : "ROCK"},
	"111" : {
		"name" : "RHYDON", 
		"type1" : "GROUND", 
		"type2" : "ROCK",
		"HP" : 105,
		"ATTACK" : 130,
		"DEFENSE" : 120,
		"SPECIAL" : 45,
		"SPEED" : 40,
		"TIER": "HIGH"
		},
	"112" : {"name" : "CHANSEY", "type1" : "NORMAL", "type2" : "NULL"},
	"113" : {"name" : "TANGELA", "type1" : "GRASS", "type2" : "NULL"},
	"114" : {"name" : "KANGASKHAN", "type1" : "NORMAL", "type2" : "NULL"},
	"115" : {"name" : "HORSEA", "type1" : "WATER", "type2" : "NULL"},
	"116" : {"name" : "SEADRA", "type1" : "WATER", "type2" : "NULL"},
	"117" : {"name" : "GOLDEEN", "type1" : "WATER", "type2" : "NULL"},
	"118" : {"name" : "SEAKING", "type1" : "WATER", "type2" : "NULL"},
	"119" : {"name" : "STARYU", "type1" : "WATER", "type2" : "NULL"},
	"120" : {"name" : "STARMIE", "type1" : "WATER", "type2" : "PSYCHIC"},
	"121" : {"name" : "MR. MIME", "type1" : "PSYCHIC", "type2" : "NULL"},
	"122" : {"name" : "SCYTHER", "type1" : "BUG", "type2" : "FLYING"},
	"123" : {"name" : "JYNX", "type1" : "ICE", "type2" : "PSYCHIC"},
	"124" : {"name" : "ELECTABUZZ", "type1" : "ELECTRIC", "type2" : "NULL"},
	"125" : {"name" : "MAGMAR", "type1" : "FIRE", "type2" : "NULL"},
	"126" : {"name" : "PINSIR", "type1" : "BUG", "type2" : "NULL"},
	"127" : {"name" : "TAUROS", "type1" : "NORMAL", "type2" : "NULL"},
	"128" : {"name" : "MAGIKARP", "type1" : "WATER", "type2" : "NULL"},
	"129" : {"name" : "GYARADOS", "type1" : "WATER", "type2" : "FLYING"},
	"130" : {"name" : "LAPRAS", "type1" : "WATER", "type2" : "ICE"},
	"131" : {"name" : "DITTO", "type1" : "NORMAL", "type2" : "NULL"},
	"132" : {"name" : "EEVEE", "type1" : "NORMAL", "type2" : "NULL"},
	"133" : {
		"name" : "VAPOREON", 
		"type1" : "WATER", 
		"type2" : "NULL",
		"HP" : 130,
		"ATTACK" : 65,
		"DEFENSE" : 60,
		"SPECIAL" : 110,
		"SPEED" : 65,
		"TIER": "MID"
		},
	"134" : {"name" : "JOLTEON", "type1" : "ELECTRIC", "type2" : "NULL"},
	"135" : {"name" : "FLAREON", "type1" : "NORMAL", "type2" : "NULL"},
	"136" : {"name" : "PORYGON", "type1" : "NORMAL", "type2" : "NULL"},
	"137" : {"name" : "OMANYTE", "type1" : "ROCK", "type2" : "WATER"},
	"138" : {"name" : "OMASTAR", "type1" : "ROCK", "type2" : "WATER"},
	"139" : {"name" : "KABUTO", "type1" : "ROCK", "type2" : "WATER"},
	"140" : {"name" : "KABUTOPS", "type1" : "ROCK", "type2" : "WATER"},
	"141" : {"name" : "AERODACTYL", "type1" : "ROCK", "type2" : "FLYING"},
	"142" : {"name" : "SNORLAX", "type1" : "SNORLAX", "type2" : "NULL"},
	"143" : {"name" : "ARTICUNO", "type1" : "ICE", "type2" : "FLYING"},
	"144" : {"name" : "ZAPDOS", "type1" : "ELECTRIC", "type2" : "FLYING"},
	"145" : {"name" : "MOLTRES", "type1" : "FIRE", "type2" : "FLYING"},
	"146" : {"name" : "DRATINI", "type1" : "DRAGON", "type2" : "NULL"},
	"147" : {"name" : "DRAGONAIR", "type1" : "DRAGON", "type2" : "NULL"},
	"148" : {"name" : "DRAGONITE", "type1" : "DRAGON", "type2" : "FLYING"},
	"149" : {"name" : "MEWTWO", "type1" : "PSYCHIC", "type2" : "NULL"},
	"150" : {"name" : "MEW", "type1" : "PSYCHIC", "type2" : "NULL"}
}
